### ISSUE TITLE
Add support for env

### ISSUE THREAD

**Issue by Wulfheart** [mabadir/laravel-cypress#2]
I think that this package offers the best approach to laravel cypress testing. Unfortunately you are assuming that everyone is using a separate domain for it. 
I'm using it by specifying a test environment and I'd love to see that this package also has the option to listen on a specific env and not on a sepcific domain.
Is this possible?

**Comment by mabadir** [comment]
Thanks for your thoughts.
The package can make use of different `.env.acceptance` file. However we will need a way to instruct Laravel to load the acceptance file instead of the standard `.env` file and hence the different domain.

Do you have specific recommendation in mind to load the difference env file?
